"""empty message

Revision ID: 58b680999b02
Revises: 0f61ca21d5a2
Create Date: 2020-05-30 16:00:29.704845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b680999b02'
down_revision = '0f61ca21d5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('administrator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('super_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('administrator_id')
    )
    op.create_table('car',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('first_registration', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('fuel', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.seller_id'], ),
    sa.PrimaryKeyConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    op.drop_table('administrator')
    # ### end Alembic commands ###
